# Generated by Django 5.1.6 on 2025-06-01 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otp_totp.totpdevice'),
        ),
    ]
